obj_class_dict:
  - obj:
      type: CircularObjects
      radius: 0.045
    radius_of_influence: 0.2
    affinities: [3, 4, 5, 7, 12, 13]
    self_affinity: 0.7
    alignment: 0.0
    name: YcbChipsCan
    is_large: True
  - obj:
      type: CircularObjects
      radius: 0.035
    radius_of_influence: 0.15
    affinities: [0, 5, 11, 12]
    self_affinity: 0.1
    alignment: 0.0
    name: YcbTomatoSoupCan
    is_large: False
  - obj:
      type: CircularObjects
      radius: 0.051
    radius_of_influence: 0.12
    affinities: [4, 5, 7, 12]
    self_affinity: 0.1
    alignment: 0.0
    name: YcbMasterChefCan
    is_large: True
  - obj:
      type: CircularObjects
      radius: 0.035
    radius_of_influence: 0.12
    affinities: [0, 5, 10, 11, 12]
    self_affinity: 0.01
    alignment: 0.0
    name: Ycbsuger1
    is_large: False
  - obj:
      type: BoxObjects
      height: 0.1
      width: 0.07
    radius_of_influence: 0.15
    affinities: [0, 2, 5, 7, 8, 10]
    self_affinity: 0.5
    alignment: 0.0
    name: YcbBleachCleanser
    is_large: True
  - obj:
      type: BoxObjects
      height: 0.165
      width: 0.07
    radius_of_influence: 0.2
    affinities: [0, 2, 4, 7, 8, 12]
    self_affinity: 0.7
    alignment: 0.0
    name: YcbCrackerBox
    is_large: True
  - obj:
      type: BoxObjects
      height: 0.03
      width: 0.07
    radius_of_influence: 0.1
    affinities: [0, 3, 5, 7, 10, 11, 12]
    self_affinity: 0.01
    alignment: 0.0
    name: YcbGelatinBox
    is_large: False
  - obj:
      type: BoxObjects
      height: 0.057
      width: 0.095
    radius_of_influence: 0.2
    affinities: [0, 2, 4, 5]
    self_affinity: 0.5
    alignment: 0.0
    name: YcbMustardBottle
    is_large: False
  - obj:
      type: BoxObjects
      height: 0.11
      width: 0.06
    radius_of_influence: 0.2
    affinities: [4, 5, 7]
    self_affinity: 0.3
    alignment: 0.0
    name: YcbOrionPie
    is_large: False
  - obj:
      type: BoxObjects
      height: 0.10
      width: 0.05
    radius_of_influence: 0.15
    affinities: [6, 11]
    self_affinity: 0.1
    alignment: 0.0
    name: YcbPottedMeatCan
    is_large: False
  - obj:
      type: BoxObjects
      height: 0.08
      width: 0.051
    radius_of_influence: 0.15
    affinities: [4, 8, 12]
    self_affinity: 0.1
    alignment: 0.0
    name: backmeel
    is_large: True
  - obj:
      type: BoxObjects
      height: 0.087
      width: 0.185
    radius_of_influence: 0.15
    affinities: [8, 12]
    self_affinity: 0.7
    alignment: 0.0
    name: collezione
    is_large: True
  - obj:
      type: BoxObjects
      height: 0.06
      width: 0.14
    radius_of_influence: 0.15
    affinities: [3, 7, 4, 5, 10, 11, 12]
    self_affinity: 0.7
    alignment: 0.0
    name: muesli
    is_large: True
  - obj:
      type: BoxObjects
      height: 0.07
      width: 0.07
    radius_of_influence: 0.15
    affinities: [3, 4, 5, 10, 11, 12]
    self_affinity: 0.1
    alignment: 0.0
    name: vollmilch
    is_large: True
  - obj:
      type: CircularObjects
      radius: 0.03
    radius_of_influence: 0.1
    affinities: [2, 4]
    self_affinity: 0.3
    alignment: 0.0
    name: cylinder_03
  - obj:
      type: CircularObjects
      radius: 0.04
    radius_of_influence: 0.1
    affinities: [ 2, 4 ]
    self_affinity: 0.3
    alignment: 0.0
    name: cylinder_04
  - obj:
      type: CircularObjects
      radius: 0.08
    radius_of_influence: 0.1
    affinities: [ 2, 4 ]
    self_affinity: 0.3
    alignment: 0.0
    name: cylinder_08
  - obj:
      type: BoxObjects
      height: 0.06
      width: 0.12
    radius_of_influence: 0.15
    affinities: [0, 1]
    self_affinity: 0.3
    alignment: 0.0
    name: box_06_12
  - obj:
      type: BoxObjects
      height: 0.09
      width: 0.14
    radius_of_influence: 0.15
    affinities: [ 1, 3 ]
    self_affinity: 0.3
    alignment: 0.0
    name: box_09_14
  - obj:
      type: BoxObjects
      height: 0.05
      width: 0.05
    radius_of_influence: 0.15
    affinities: [ 2, 0 ]
    self_affinity: 0.3
    alignment: 0.0
    name: box_05_05
